apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kafka-ui
spec:
  ingressClassName: nginx
  rules:
    - host: "kafka-ui"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: kafka-ui
              port: 
                number: 80