stages:
  - test
  - build
  - deploy

test:
    stage: test
    tags:
        - testing
    script:
        - cd /home/ubuntu/cloudcompa2
        - ls
        - git pull
        - python3 -m unittest discover ./test

build:
    stage: build
    tags:
        - building
    script:
        - cd cloudcompa2
        - make -C ./backend doc
        - make -C ./test teardown
        - make - C ./test deploy

deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - cd cloudcompa2
    - make -C backend/api teardown
    - make -C backend/api deploy
