stages:
  - deploy
  - test

deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - echo "$KUBECONFIG"
    - make -C ./backend doc
    - make -C ./docs teardown
    - make -C ./docs deploy
    - make -C ./backend/api teardown
    - make -C ./backend/api deploy

test:
    stage: test
    tags:
        - testing
    script:
        - pip3 install -r /home/ubuntu/environments/python/requirements.txt
        - python3 -m unittest discover ./test
