stages:
  - test
  - deploy

test:
    image: python:latest
    stage: test
    tags:
        - testing
    script:
        - pip3 install requests
        - pip3 install pandas
        - python3 -m unittest discover ./test

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "cd cloudcompa2; git pull"