stages:
  - deploy
  - test

deploy:
  stage: deploy
  tags:
    - deployment
  only:
    - master
  script:
    - make -C ./backend doc
    - make -C ./docs teardown
    - make -C ./docs deploy
    - make -C ./backend/api teardown
    - make -C ./backend/api deploy
    - make -C ./backend/fission/functions teardown
    - make -C ./backend/fission/functions deploy

test:
    stage: test
    tags:
        - testing
    only:
      - master
    script:
        - pip3 install -r /home/ubuntu/environments/python/requirements.txt
        - python3 -m unittest discover ./test
    after_script:
      - >
        if [ $CI_JOB_STATUS != 'success' ]; then
          git reset --hard HEAD~1
          make -C ./backend doc
          make -C ./docs teardown
          make -C ./docs deploy
          make -C ./backend/api teardown
          make -C ./backend/api deploy
          make -C ./backend/fission/functions teardown
          make -C ./backend/fission/functions deploy
        fi
