stages:
  - test
  - build
  - deploy

test:
    stage: test
    tags:
        - testing
    script:
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "cd cloudcompa2; git pull"

build:
    stage: build
    tags:
        - building
    script:
        - cd cloudcompa2
        - make -C ./backend doc
        - make -C ./test teardown
        - make - C ./test deploy

deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - cd cloudcompa2
    - make -C backend/api teardown
    - make -C backend/api deploy