stages:
  - deploy
  - test

deploy:
  stage: deploy
  tags:
    - deployment
  only:
    - master
  script:
    - echo "$KUBECONFIG"
    - make -C ./backend doc
    - make -C ./docs teardown
    - make -C ./docs deploy
    - make -C ./backend/api teardown
    - make -C ./backend/api deploy

test:
    stage: test
    tags:
        - testing
    only:
      - master
    script:
        - pip3 install -r /home/ubuntu/environments/python/requirements.txt
        - python3 -m unittest discover ./test
    after_script:
      - >
        if [ $CI_JOB_STATUS == 'success' ]; then
          echo 'This will only run on success'
        else
          echo 'This will only run when job failed or is cancelled'
          git reset HEAD~1
        fi
