# Team 69
# Dillon Blake 1524907
# Andrea Delahaye 1424289
# Yue Peng 958289
# Jeff Phan 1577799
# Alistair Wilcox 212544

datadog:
  apiKeyExistingSecret: datadog-secret
  site: us5.datadoghq.com
  logs:
    enabled: true
    containerCollectAll: true
  ignoreAutoConfig:
    - docker_daemon
    - elastic
  confd:
    elastic.yaml: |-
      init_config:
      instances:
        - url: "https://elasticsearch.elastic.svc.cluster.local:9200"
          username: elastic
          password: cloudcomp
          tls_verify: false
          tls_ignore_warning: True
          auth_type: basic
          cluster_stats: true
          tags:
          - service.name:elasticsearch
agents:  
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"